export const DEFINE_SERVICE = 'DEFINE_SERVICE';
export const SET_USER_VALUE = 'SET_USER_VALUE';
export const DEFINE_PRICE = 'DEFINE_PRICE';
export const DELETE_RECORD = 'DELETE_RECORD';
export const CLEAR_INPUT = 'CLEAR_INPUT';
export const EDIT_INPUT = 'EDIT_INPUT';
export const FILTER = 'FILTER';

export default {
  DEFINE_SERVICE,
  SET_USER_VALUE,
  DEFINE_PRICE,
  DELETE_RECORD,
  CLEAR_INPUT,
  EDIT_INPUT,
  FILTER
};
